directories:
  - path: "~/.local/state/opencode"
entries:
  - source: "kv.json"
    target: "~/.local/state/opencode/kv.json"
  - source: "model.json"
    target: "~/.local/state/opencode/model.json"
